package easy

/**
 * 389. Find the Difference
 * https://leetcode.com/problems/find-the-difference/
 *
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 */

class Easy389 {

    fun findTheDifference(s: String, t: String): Char {
        var sum = t[t.length - 1].code
        s.forEachIndexed { index, value ->
            sum += t[index].code - value.code
        }
        return sum.toChar()
    }
}

fun main() {
    println(Easy389().findTheDifference("abcd", "abcde"))
    println(Easy389().findTheDifference("", "y"))
    println(Easy389().findTheDifference("a", "aa"))
    println(Easy389().findTheDifference("ae", "aea"))
}